Lexik\Bundle\MailerBundle\Entity\LayoutTranslation:
    type: mappedSuperclass
    fields:
        lang:
            column: lang
            type: string
            length: 2
        body:
            column: body
            type: text
        createdAt:
            column: created_at
            type: datetime
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [updateTimestamps]
        preUpdate: [updateTimestamps]
